### ISSUE TITLE
Create crontab script to update user results

### ISSUE THREAD

**Issue by ngrebenshikov** [abakan-student-projects/scholae-web#67]
A script should initiate jobs if there are no the same job in progress.

A script should find the users whose results should be refreshed this time and create jobs to refresh results from codeforces.

Time to refresh is a day after last refreshing.

The script should be run every minute.

Subtasks:

- [x] Create a task in the CLI
- [x] Prepare CRONTAB configuration line. Put it into the documentation.

**Comment by lipgen** [comment]
#79
